In [2]:
import numpy as np

In [2]:
##生成特征矩阵
np.eye(5,dtype=int)       

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
np.eye(4,dtype=int,k=1)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [5]:
np.eye(4,dtype=int,k=2)

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [3]:
arr=np.arange(32).reshape(4,8)

In [4]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [5]:
arr[[0,1,2,3],[1,2,3,4]]

array([ 1, 10, 19, 28])

In [6]:
arr=np.arange(24).reshape(4,6)


In [7]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
arr.transpose()


array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [9]:
arr=np.arange(10)

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr.sqrt()  ##这个是不行的，因为np是这个库里面的函数，不是数组的成员

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [21]:
arr=np.random.randn(10)

In [22]:
arr

array([ 0.47793663,  0.88367405, -0.60618997, -2.31442197,  0.48498994,
        0.78408367, -0.5741835 , -2.44817335,  0.86662492,  0.77477577])

In [25]:
i,f=np.modf(arr)

In [26]:
i

array([ 0.47793663,  0.88367405, -0.60618997, -0.31442197,  0.48498994,
        0.78408367, -0.5741835 , -0.44817335,  0.86662492,  0.77477577])

In [27]:
f

array([ 0.,  0., -0., -2.,  0.,  0., -0., -2.,  0.,  0.])

In [30]:
arr.dtype=int   

In [32]:
arr

array([ 4602281360834235979,  4606134647770530922, -4619736743430444514,
       -4610978003085540032,  4602408421943768639,  4605237617398258326,
       -4620025032136965386, -4610676821754613575,  4605981082911541209,
        4605153779323334551])

In [41]:
~arr  ##改变数子的符号   

array([-4602281360834235980, -4606134647770530923,  4619736743430444513,
        4610978003085540031, -4602408421943768640, -4605237617398258327,
        4620025032136965385,  4610676821754613574, -4605981082911541210,
       -4605153779323334552])

In [42]:
np.logical_not(arr)

array([False, False, False, False, False, False, False, False, False,
       False])

In [50]:
arr=np.ones_like(3)

In [51]:
arr

array(1)

In [53]:
arr=np.ones_like((520,1314))

In [55]:
arr

array([1, 1])

In [57]:
arr=np.arange(9).reshape(3,3)

In [58]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
arr=np.ones_like(arr)

In [60]:
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [63]:
arr=np.ones((3,3))

In [65]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
obj=np.subtract(arr,1)   ##去除指定的元素

In [69]:
obj

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
arr1=np.arange(9).reshape(3,3)

In [72]:
arr2=np.arange(9).reshape(3,3)

In [73]:
arr=arr1*arr2

In [74]:
arr

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [75]:
arr=np.multiply(arr1,arr2)    ##乘法跟*是一样的

In [76]:
arr

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [77]:
arr1/arr2

<ipython-input-77-e677913e0f55>:1: RuntimeWarning: invalid value encountered in true_divide
  arr1/arr2


array([[nan,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [78]:
np.power(arr1,arr2)    ##第二个参数作为幂次

array([[       1,        1,        4],
       [      27,      256,     3125],
       [   46656,   823543, 16777216]])

In [79]:
arr1%5

array([[0, 1, 2],
       [3, 4, 0],
       [1, 2, 3]])

In [82]:
np.mod(arr1,5)

array([[0, 1, 2],
       [3, 4, 0],
       [1, 2, 3]])

In [83]:
arr=np.random.randn(4,4)

In [84]:
arr

array([[-1.18829812,  1.00012543,  0.85752154, -1.04047989],
       [ 0.78077666, -0.22186423,  0.52896081,  0.57759839],
       [ 0.81251926, -0.73747018,  0.25062141, -1.6208634 ],
       [-0.58821175,  0.09462481, -0.43753957, -0.53489256]])

In [85]:
arr>0

array([[False,  True,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True, False],
       [False,  True, False, False]])

In [87]:
np.where(arr>0,-2,2)   ##where

array([[ 2, -2, -2,  2],
       [-2,  2, -2, -2],
       [-2,  2, -2,  2],
       [ 2, -2,  2,  2]])

In [89]:
np.where(arr>0,-2,arr)

array([[-1.18829812, -2.        , -2.        , -1.04047989],
       [-2.        , -0.22186423, -2.        , -2.        ],
       [-2.        , -0.73747018, -2.        , -1.6208634 ],
       [-0.58821175, -2.        , -0.43753957, -0.53489256]])

In [90]:
arr=np.random.randn(5,4)

In [91]:
arr

array([[-1.05571311, -0.88079263,  0.0639413 , -0.23853896],
       [ 1.01496325, -2.35035178,  0.56304555, -1.60599989],
       [-0.4678158 ,  0.25656071, -0.71589397, -1.41397213],
       [-1.33093789,  0.0196747 ,  1.5377504 ,  0.65741744],
       [-0.96289842, -0.08742375,  0.92815192, -0.2940408 ]])

In [93]:
np.mean(arr)

-0.3181436936416319

In [94]:
arr.mean()

-0.3181436936416319

In [3]:
obj = np.random.randn(10)

In [5]:
obj

array([-0.1147654 ,  0.36467098,  0.64363408, -1.41058494,  0.15815202,
       -1.85664043, -1.29252911,  1.08449885, -1.76056401, -0.82859373])

In [6]:
obj.sort()

In [8]:
obj      ##也就是说sort方法直接改变了内部的顺序

array([-1.85664043, -1.76056401, -1.41058494, -1.29252911, -0.82859373,
       -0.1147654 ,  0.15815202,  0.36467098,  0.64363408,  1.08449885])

In [10]:
##计算唯一值

In [14]:
names = np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])

In [17]:
np.unique(names)    ##这个不仅算唯一值，而且还要排序
sorted(set(names))    ##等价

['Bob', 'Joe', 'Will']

In [19]:
arr1=np.arange(5)
arr2=np.arange(2,8)

In [21]:
np.intersect1d(arr1,arr2)   ##算交集，并且排序

array([2, 3, 4])

In [23]:
np.union1d(arr1,arr2)     ##并集，并且排序

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
np.in1d(arr1,arr2)    ##看arr1的元素是不是在arr2中

array([False, False,  True,  True,  True])

In [25]:
np.setdiff1d(arr1,arr2)     ##在arr1中，但是不再arr2中的元素  arr1-arr2

array([0, 1])

In [26]:
np.setxor1d(arr1,arr2)    ##异或集

array([0, 1, 5, 6, 7])

In [29]:
##线性代数
import numpy as np

In [41]:
x=np.array([[1,2,3],[4,5,6]])

In [43]:
y=np.array([[6,23],[-1,7],[8,9]])

In [44]:
np.dot(x,y)   ##点乘

array([[ 28,  64],
       [ 67, 181]])

In [45]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [46]:
x@y    ##@是点乘的意思

array([[ 28,  64],
       [ 67, 181]])

In [48]:
##常用numpy.linalg 函数

In [49]:
from numpy.linalg import inv,qr    ##117页

In [50]:
x = np.random.randn(5,5)

In [51]:
x

array([[-1.31158941,  0.81349892,  0.57135821,  0.2080375 ,  0.47505482],
       [ 0.45736118, -2.16034396,  0.16520624,  1.08961917, -1.86645372],
       [ 0.37597109,  0.17112959, -0.00226491, -1.56559209,  0.21215891],
       [ 0.68128639, -1.9061861 ,  1.06460799,  0.07653662,  1.8985586 ],
       [ 0.5512562 ,  1.06906221,  1.14128776, -0.09213867, -1.36599805]])

In [52]:
mat = x.T.dot(x)

In [53]:
mat

array([[ 2.83883483, -2.70002573,  0.67976488, -0.3617763 , -0.85650749],
       [-2.70002573, 10.13459133, -0.70172394, -2.69702804, -0.62439764],
       [ 0.67976488, -0.70172394,  2.78967636,  0.2787465 ,  0.42481996],
       [-0.3617763 , -2.69702804,  0.2787465 ,  3.69597552, -1.99587835],
       [-0.85650749, -0.62439764,  0.42481996, -1.99587835,  9.22481337]])

In [54]:
inv(mat)   ##计算逆矩阵

array([[ 0.86854865,  0.35841991, -0.20259698,  0.47956105,  0.21799115],
       [ 0.35841991,  0.27966335, -0.06663468,  0.31028855,  0.12241076],
       [-0.20259698, -0.06663468,  0.41600927, -0.13901164, -0.07255559],
       [ 0.47956105,  0.31028855, -0.13901164,  0.67174177,  0.21726844],
       [ 0.21799115,  0.12241076, -0.07255559,  0.21726844,  0.18727842]])

In [63]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -4.90428455e-17, -9.48418680e-17,
        -1.42678059e-16, -8.62116136e-17],
       [ 4.57499000e-16,  1.00000000e+00,  1.70091296e-16,
        -4.28510959e-16, -1.28931409e-16],
       [ 1.68615712e-17,  1.38781798e-17,  1.00000000e+00,
         3.01779683e-17,  6.40830431e-18],
       [-1.35446886e-16, -2.57968953e-16,  1.12054133e-16,
         1.00000000e+00, -2.00727168e-16],
       [-1.34459101e-16, -9.05664131e-17,  1.09624164e-16,
        -6.40462294e-17,  1.00000000e+00]])

In [ ]:
##计算qr 分解

In [64]:
q,r = qr(mat)

In [65]:
q

array([[-0.69518153, -0.44169075,  0.05132502,  0.04792992,  0.56276139],
       [ 0.66118958, -0.66246185, -0.09753351, -0.12081229,  0.31601305],
       [-0.16646266, -0.09786668, -0.95890152, -0.09019914, -0.18730798],
       [ 0.08859276,  0.49138213, -0.11390677, -0.65047385,  0.56089566],
       [ 0.20974386,  0.33914494, -0.23534245,  0.74286943,  0.48347405]])

In [66]:
r

array([[-4.08358783,  8.32480431, -1.28711119, -1.66933409,  1.86989394],
       [ 0.        , -6.98956098,  0.17264971,  3.05843572,  2.89818517],
       [ 0.        ,  0.        , -2.70342365,  0.0259103 , -2.33406725],
       [ 0.        ,  0.        ,  0.        , -3.60346093,  8.14716275],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  2.58157903]])

In [67]:
mat

array([[ 2.83883483, -2.70002573,  0.67976488, -0.3617763 , -0.85650749],
       [-2.70002573, 10.13459133, -0.70172394, -2.69702804, -0.62439764],
       [ 0.67976488, -0.70172394,  2.78967636,  0.2787465 ,  0.42481996],
       [-0.3617763 , -2.69702804,  0.2787465 ,  3.69597552, -1.99587835],
       [-0.85650749, -0.62439764,  0.42481996, -1.99587835,  9.22481337]])

In [1]:
import numpy as np

In [3]:
#伪随机数生成

In [4]:
##normal 生成多种概率分别下的完整样本数组

In [5]:
samples = np.random.normal(size=(4,4))  ##4*4的正态分布样本数组

In [6]:
samples

array([[-2.90525066,  0.02948251, -0.68964314, -0.37432241],
       [-0.14799507,  1.09388626, -0.22734819, -0.82912388],
       [ 1.16120063,  1.45052885,  0.1827467 , -1.32311111],
       [ 2.18035458,  0.5968726 , -0.5173006 , -1.53567331]])

In [7]:
##但是numpy.random 一次只能生成一个值

In [8]:
arr = np.random.permutation(10)    ##隐式的调用了np.arange

In [9]:
arr

array([5, 2, 8, 4, 0, 7, 3, 1, 9, 6])

In [10]:
arr = np.arange(9).reshape((3,3))

In [11]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.random.permutation(arr)

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [1]:
import numpy as np

In [2]:
names = np.array(['小明','小黄','小花','小明','小花','小兰','小白'])

In [3]:
print("去重后的数组为",np.unique(names))

去重后的数组为 ['小兰' '小明' '小白' '小花' '小黄']


In [4]:
#跟np.unique等价的python代码实现过程

In [5]:
print('去重后的数组为',sorted(set(names)))

去重后的数组为 ['小兰', '小明', '小白', '小花', '小黄']


In [6]:
ints = np.array([1,2,3,4,4,5,6,6,7,8,8,9,10])

In [7]:
print('创建的数组为',ints)

创建的数组为 [ 1  2  3  4  4  5  6  6  7  8  8  9 10]


In [8]:
print('去重后的数组为',np.unique(ints))

去重后的数组为 [ 1  2  3  4  5  6  7  8  9 10]


In [9]:
##使用tile函数实现数据重复

In [10]:
arr = np.arange(5)

In [11]:
print('创建的数组为',arr)

创建的数组为 [0 1 2 3 4]


In [12]:
print('重复后数组为',np.tile(arr,3))

重复后数组为 [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


In [13]:
arr = np.random.randint(0,10,size=(3,3))

In [14]:
print('创建的数组为',arr)

创建的数组为 [[5 0 9]
 [7 7 8]
 [6 1 5]]


In [15]:
print('重复的数组为: ',arr.repeat(2,axis=0))

重复的数组为:  [[5 0 9]
 [5 0 9]
 [7 7 8]
 [7 7 8]
 [6 1 5]
 [6 1 5]]


In [17]:
print('重复的数组为: ',arr.repeat(2,axis = 1))

重复的数组为:  [[5 5 0 0 9 9]
 [7 7 7 7 8 8]
 [6 6 1 1 5 5]]


In [ ]:
##当axis参数为0时，表示沿着纵轴进行计算，当axis为1时，表示沿着横轴进行计算

In [18]:
arr = np.arange(20).reshape(4,5)

In [19]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
print('数组的和为:',np.sum(arr))

数组的和为: 190


In [21]:
print('数组的纵轴的和为:',np.sum(arr,axis=0))

数组的纵轴的和为: [30 34 38 42 46]


In [22]:
print('数组的横轴的和为:',np.sum(arr,axis=1))

数组的横轴的和为: [10 35 60 85]


In [23]:
print('数组的均值为:',np.mean(arr))   

数组的均值为: 9.5


In [24]:
print('数组的纵轴的均值为:',arr.mean(axis = 0))

数组的纵轴的均值为: [ 7.5  8.5  9.5 10.5 11.5]
