In [2]:
import numpy as np

In [3]:
arr = np.empty((8,4))

In [4]:
arr

array([[4.66263256e-310, 0.00000000e+000, 6.94251001e-310,
        6.94253665e-310],
       [6.94253658e-310, 6.94253655e-310, 6.94253658e-310,
        6.94253664e-310],
       [6.94251023e-310, 6.94252717e-310, 6.94253656e-310,
        6.94253656e-310],
       [6.94253664e-310, 6.94253665e-310, 6.94253664e-310,
        6.94252717e-310],
       [6.94251001e-310, 6.94253596e-310, 6.94253601e-310,
        6.94253662e-310],
       [6.94253664e-310, 6.94253666e-310, 6.94253606e-310,
        6.94253665e-310],
       [6.94253665e-310, 6.94253659e-310, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [5]:
for i in range(8):
    arr[i] = i

In [6]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [8]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [11]:
arr = np.arange(32).reshape((8,4))

In [12]:
arr 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [14]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [16]:
arr[[1,5,7,2]][:,[0,3,1,2]]    #注意,神奇的索引与切片不一样,他总是将数据复制到一个心的数组中

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [17]:
##modf返回数组的小数部分和整数部分

In [19]:
arr = np.random.randn(7)*5

In [20]:
remainder, whole = np.modf(arr)

In [21]:
remainder

array([-0.01375874,  0.60997666, -0.85968035,  0.82144043, -0.85271688,
       -0.97222882, -0.78620047])

In [22]:
whole

array([ -4.,   8.,  -3.,   0.,  -0.,  -0., -12.])

In [23]:
##布尔数组的方法

In [24]:
arr = np.random.randn(100)

In [25]:
arr

array([ 2.21280556e-01,  6.76682802e-01, -1.36468175e+00, -6.15965374e-01,
       -1.49957384e+00,  1.17037429e+00,  8.09999784e-01, -2.31414742e-01,
        7.06650922e-01,  6.03658099e-01, -2.37728879e-01, -2.07711339e+00,
       -1.23581054e+00,  6.09567961e-01, -4.72507793e-01, -7.51010299e-01,
       -1.10615087e-02,  3.93110784e-01, -1.30734246e-01, -9.14921735e-01,
       -4.30087441e-01, -1.14842614e+00, -5.56213930e-01, -1.11517006e-01,
       -1.12114906e+00, -1.45531698e+00,  8.21384549e-01, -6.60240765e-01,
       -1.01486903e+00, -2.02546404e+00,  3.12993009e-01,  1.86014443e+00,
       -1.94270703e+00,  1.09674752e+00, -3.19743425e-01, -5.27148852e-01,
       -8.17840388e-01,  3.45889352e-02, -8.66487934e-01, -6.13915328e-01,
        2.16242819e-01,  2.00060970e+00,  4.18147565e-01, -1.08998125e-01,
        1.73029462e-02, -1.89546979e+00,  5.22746996e-01,  3.14340200e-01,
       -5.13059681e-01, -1.25505538e+00, -5.84538142e-01, -1.07230129e+00,
       -6.74627524e-01, -

In [26]:
(arr > 0).sum()     //这个就是返回正数的个数

37

In [27]:
##any只要有一个true就是true 
##all 全部是true就是true

In [28]:
bools = np.array([False,False,True,False])

In [29]:
bools.any()

True

In [30]:
bools.all()

False

In [31]:
#使用数组进行文件输入和输出

In [32]:
arr = np.arange(10)

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.save("some_array",arr)

In [36]:
np.load("some_array.npy")    ##记住这里必须要加上npy这个后缀

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#将数组作为参数传递给参数

In [37]:
np.savez('array_archive.npz',a = arr, b = arr)

In [38]:
arch = np.load('array_archive.npz')

In [39]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#中缀操作符

In [43]:
x = np.array([[1,2,3],[4,5,6]])

In [45]:
x @ np.ones(3)

array([ 6., 15.])

In [46]:
np.ones(3)

array([1., 1., 1.])

In [48]:
arr = np.random.randn(4,4)

In [51]:
arr > 0


array([[ True,  True, False,  True],
       [False, False, False, False],
       [False,  True,  True, False],
       [False,  True, False,  True]])

In [52]:
arr[arr>0]

array([0.85218812, 0.5119974 , 0.68554139, 1.8697318 , 0.22928077,
       0.5203641 , 0.77822919])